# Generated by Django 3.1 on 2020-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallTiles_18_12_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('tile_number', models.CharField(max_length=128)),
                ('light', models.ImageField(upload_to='')),
                ('high_lighter_1', models.ImageField(upload_to='')),
                ('high_lighter_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('high_lighter_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('dark', models.ImageField(upload_to='')),
            ],
        ),
    ]
