# Generated by Django 3.1 on 2020-09-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallsimulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walltiles_18_12_model',
            old_name='dark',
            new_name='dark_image_url',
        ),
        migrations.RenameField(
            model_name='walltiles_18_12_model',
            old_name='high_lighter_1',
            new_name='high_lighter_1_image_url',
        ),
        migrations.RenameField(
            model_name='walltiles_18_12_model',
            old_name='high_lighter_2',
            new_name='high_lighter_2_image_url',
        ),
        migrations.RenameField(
            model_name='walltiles_18_12_model',
            old_name='high_lighter_3',
            new_name='high_lighter_3_image_url',
        ),
        migrations.RenameField(
            model_name='walltiles_18_12_model',
            old_name='light',
            new_name='light_image_url',
        ),
    ]
