# Generated by Django 3.1 on 2020-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallsimulator', '0002_auto_20200921_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walltiles_18_12_model',
            name='dark_image_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='walltiles_18_12_model',
            name='high_lighter_1_image_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='walltiles_18_12_model',
            name='high_lighter_2_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='walltiles_18_12_model',
            name='high_lighter_3_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='walltiles_18_12_model',
            name='light_image_url',
            field=models.CharField(max_length=1024),
        ),
    ]
